AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Microservicio simple con AWS SAM

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      CodeUri: .
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
